#### Makefile
#### version 5.1

# Note : ne pas mettre de commentaires a coté des regles !

# Spécifie le compilateur à utiliser
CC=gcc
# Définit les options de compilation
CFLAGS=-g -I$(IDIR)

# repertoir des "objects"  (.o)
ODIR=../obj
# repertoir des "includes" (.h)
IDIR =../headers
# repertoir des "binaries" (executables)
BDIR =../exec
# repertoir des fichiers sources (.c)
SDIR=../src

#Liste des fichiers d'en-tete (les .h)
_DEPS = FonctionLecture.h FonctionChiffrement.h FonctionMenu.h
DEPS = $(patsubst %,$(IDIR)/%,$(_DEPS))

#Liste des fichiers objets (les .o)
_OBJ = testMain.o FonctionLecture.o FonctionChiffrement.o FonctionMenu.o
OBJ = $(patsubst %,$(ODIR)/%,$(_OBJ))

#Liste des fichiers pour le test :


# Règle pour générer les fichier objet (.o) à partir des fichier source (.c)
# 
# "%.o : %.c"	: signifie que le .o depend du .c de meme nom
# $(DEPS)		: ajoute la liste des fichiers d'en-tete prérequis
#
# -c 			: signifie qu'on veux generer le .o
# -o $@ 		: le .o auras le nom de ce qui est a gauche du ":"
# $< 			: le premier fichier source prérequis
# $(CFLAGS)		: les options
$(ODIR)/%.o: $(SDIR)/%.c $(DEPS)
	$(CC) -c -o $@ $< $(CFLAGS)

# Regle pour génerer le fichier executable dans le repertoire des executables
#
# $(OBJ) 		: la liste des fichiers objets prérequis
# -o $@			: le .o auras le nom de ce qui est a gauche du ":"
# $^			: le nom de tous les fichiers prérequis
# $(CFLAGS)		: les options
$(BDIR)/testMain: $(OBJ)
	$(CC) -o $@ $^ $(CFLAGS)


# Ignore tout fichier qui s'appelle "clean"
# Evite d'avoir " 'clean' is up to date" si on a un fichier qui s'appelle "clean"
.PHONY: clean 

# Supprime:
# les fichier .o dans le repertoire des objets
# les fichiers .~ (fichiers temporaires)
# les fichiers core ("core dump" en cas d'erreur)
# les fichier .~ dans le repertoire des "includes" (repertoire des .h)
clean:
	rm -f $(ODIR)/*.o *~ core $(IDIR)/*~ 
